import { Roboto } from 'next/font/google'
import MainLayout from 'layouts/MainLayout'
import { ReactQueryProvider, NextAuthProvider } from 'providers'
import 'ui/globals.css'
import 'ui/tailwind.scss'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'My Salon - (business)',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <MainLayout>{children}</MainLayout>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
