import { Poppins } from 'next/font/google'
import MainLayout from './MainLayout'
import { ReactQueryProvider, NextAuthProvider } from 'providers'
import Subnav from './Subnav'
import 'ui/tailwind.scss'

const poppins = Poppins({ subsets: ['latin'], weight: '500' })

export const metadata = {
  title: 'My Salon - (admin)',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, ...props }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <MainLayout title="Admin">{children}</MainLayout>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
